name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.1
homepage: https://github.com/xmany/GeoFlutterFire

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.0.0
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
