name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 2.2.1
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.0+2
  rxdart: ^0.24.1

flutter:
  plugin:
    platforms:
      android:
        package: com.noeatsleepdev.geoflutterfire
        pluginClass: GeoflutterfirePlugin
      ios:
        pluginClass: GeoflutterfirePlugin
